name: goflex
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.5.0
  flutter_svg: ^2.0.7
  image_cropper: ^4.0.1
  image_picker: ^1.0.0
  flutter_image_compress: ^2.1.0
  cupertino_icons: ^1.0.2
  location: ^5.0.3
  google_maps_flutter: ^2.1.9
  geocoder2: ^1.1.2
  path_provider: ^2.1.1
  dio: ^5.3.3
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.5
  pull_to_refresh: ^2.0.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  flutter_slidable: ^3.0.1
  http: ^0.13.6
  flutter_polyline_points: ^1.0.0
  flutter_datetime_picker_plus: ^2.1.0
  intl: ^0.18.0
  app_tracking_transparency: ^2.0.4

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"
  image: assets/icons/goflex.png
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  flutter_lints: ^3.0.1
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  

  assets:
    - assets/icons/
    - assets/images/
